//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtoCommerce.Storefront.ContactExt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactExt
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Division { get; set; }
        public string District { get; set; }
        public string PostalCode { get; set; }
        public string Address { get; set; }
        public bool IsRunningStore { get; set; }
        public string newMemberType { get; set; }
        public string CatalogType { get; set; }
        public string CompanyName { get; set; }
        public string TaxId { get; set; }
        public string BusinessOwner { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
    }
}
